# Generated by Django 4.2.2 on 2024-02-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_remove_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='non-ac', max_length=8),
            preserve_default=False,
        ),
    ]
