# Generated by Django 4.2.2 on 2024-02-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_student_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hostel.attendance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='hostel.student'),
        ),
    ]
