# Generated by Django 4.2.2 on 2024-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_student_attendance_alter_attendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
