# Generated by Django 4.2.2 on 2024-03-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
