# Generated by Django 4.2.2 on 2024-03-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0012_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=150),
        ),
    ]
